### ISSUE TITLE
3.4.5 화면 접근 방법 보충 설명 필요

### ISSUE THREAD

**Issue by seonchg** [krazure/hands-on-lab#3]
Azure 에 익숙하지 않아서 3.4.5 를 따라하는데 어려움이 있었습니다. 화면 접근 방법을 보충해주시면 더 좋을 것 같습니다. 감사합니다

**Comment by kimsejun2000** [comment]
어느 경로의 3.4.5를 말씀하시는지요? 링크를 보충해주시면 수정하겠습니다.

**Comment by seonchg** [comment]
https://github.com/krazure/hands-on-lab/blob/master/SAL%201803%20내%20손으로%20만들어보는%20Azure%2C%20Rancher%2C%20Kubernetes%20(ARK)%20클러스터/3.%20Rancher%20클러스터%20구축.md

이 경로의 3.4.5 입니다.

**Comment by seonchg** [comment]
https://github.com/krazure/hands-on-lab/blob/master/SAL%201803%20내%20손으로%20만들어보는%20Azure%2C%20Rancher%2C%20Kubernetes%20(ARK)%20클러스터/4.%20실제%20앱%20배포하기.md

죄송합니다. 이 경로네요.
